import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Header from './header'
import Nav from './navtabs'


const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ['latin'],
  weight: ['400', '700'],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${outfit.variable} antialiased`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
